server:
  port: 8888

spring:
  application:
    name: zpy_blog
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  # 数据库连接字符集配置
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # 文件上传
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 3MB
  # redis
  redis:
    host: localhost
    port: 6379
    database: 2


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:com/itzpy/blog/dao/mapper/*.xml
  type-aliases-package: com.itzpy.blog.dao.pojo

# 七牛云配置
qiniu:
  accessKey: MeFdLEjuVOdc5GeKBWiJS1Ml40w5utJmUsYZs6rK
  accessSecretKey: EQ3swI5vZ9Xo8bE56WeQNLEnX2fPtiY2sdRT81wN

# JWT 自定义配置
jwt:
  token-expiration: 86400000  # 24小时毫秒数 (24 * 60 * 60 * 1000)
  secret: zpy_blog            # JWT 密钥
  salt: zpy_blog              # 加密盐值
  
# AuthorId自定义：
authorId: 1234

# 热门标签数量配置
hot:
  tag:
    num: 6